# sandbox
# bot.sandbox.enable=true
# [bot]
# bot.appid=?
# bot.secret=?
# bot.webhook.port=8080
# [ai chat]
# bot.message.ai.chat.enable=false
# bot.message.ai.chat.baseUrl=
# bot.message.ai.chat.apiKey=
# bot.message.ai.chat.model=
# bot.message.ai.chat.prompt=
# [ai image]
# bot.message.ai.image.enable=false
# bot.message.ai.image.baseUrl=
# bot.message.ai.image.apiKey=
# bot.message.ai.image.model=
# bot.message.ai.image.keywords=图片,生成图片

